import type { INodeProperties } from 'n8n-workflow';

export const smarttapDescription: INodeProperties[] = [
		{
			"displayName": "Operation",
			"name": "operation",
			"type": "options",
			"noDataExpression": true,
			"displayOptions": {
				"show": {
					"resource": [
						"Smarttap"
					]
				}
			},
			"options": [
				{
					"name": "Walletobjects Smarttap Insert",
					"value": "Walletobjects Smarttap Insert",
					"action": "Walletobjects Smarttap Insert",
					"description": "Inserts the smart tap.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/walletobjects/v1/smartTap"
						}
					}
				}
			],
			"default": ""
		},
		{
			"displayName": "POST /walletobjects/v1/smartTap",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Smarttap"
					],
					"operation": [
						"Walletobjects Smarttap Insert"
					]
				}
			}
		},
		{
			"displayName": "Id",
			"name": "id",
			"type": "string",
			"default": "",
			"description": "The unique identifier for a smart tap. This value should follow the format issuer ID.identifier where the former is issued by Google and latter is the Smart Tap id. The Smart Tap id is a Base64 encoded string which represents the id which was generated by the Google Pay app.",
			"routing": {
				"send": {
					"property": "id",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Smarttap"
					],
					"operation": [
						"Walletobjects Smarttap Insert"
					]
				}
			}
		},
		{
			"displayName": "Infos",
			"name": "infos",
			"type": "json",
			"default": "[\n  {\n    \"signUpInfo\": {}\n  }\n]",
			"description": "Communication from merchant to user.",
			"routing": {
				"send": {
					"property": "infos",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Smarttap"
					],
					"operation": [
						"Walletobjects Smarttap Insert"
					]
				}
			}
		},
		{
			"displayName": "Kind",
			"name": "kind",
			"type": "string",
			"default": "",
			"description": "Identifies what kind of resource this is. Value: the fixed string `\"walletobjects#smartTap\"`.",
			"routing": {
				"send": {
					"property": "kind",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Smarttap"
					],
					"operation": [
						"Walletobjects Smarttap Insert"
					]
				}
			}
		},
		{
			"displayName": "Merchant Id",
			"name": "merchantId",
			"type": "string",
			"default": "",
			"description": "Smart Tap merchant ID of who engaged in the Smart Tap interaction.",
			"routing": {
				"send": {
					"property": "merchantId",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Smarttap"
					],
					"operation": [
						"Walletobjects Smarttap Insert"
					]
				}
			}
		},
];
